Tugas2PPWB2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import forum.urls as forum
import fitur1B.urls as fitur1B
import fitur2.urls as fitur2
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^company/forum/', include(forum,namespace='forum')),
    url(r'^fitur1B/', include(fitur1B,namespace='fitur1B')),
    url(r'^company/profile/', include(fitur2,namespace='fitur2')),
    url(r'^$', RedirectView.as_view(url="/fitur1B/", permanent='true'),name='index')
]

fitur1B/urls.py
from django.conf.urls import url
from .views import index, add_comment

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_comment/$', add_comment, name='add_comment'),
]

fitur2/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index')
]

forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum')
]

fitur1B/models.py
from django.db import models
from forum.models import Todo
class Komentar(models.Model):
    forum = models.ForeignKey(Todo, null=True)
    nama = models.CharField('nama', max_length=400, default='DEFAULT VALUE')
    isi = models.CharField('isi', max_length=400, default='DEFAULT VALUE')

fitur2/models.py
from django.db import models

# Create your models here.

forum/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    # title = models.CharField(max_length=27)
    description = models.TextField()
    nomor = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

forum/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 48,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukkan pernyataan...'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

fitur1B/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Komentar
from forum.models import Todo
import json

# Create your views here
response = {'author': 'Yesica AsikBanget Company'}
def index(request):
    # html = 'fitur1B/fitur1B.html'
    # return render(request, html, response)
    forum1 = Todo.objects.all()
    komentar = kumpulkan_komentar(forum1)
    html = 'fitur1B/fitur1B.html'
    response['gambar'] = 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0NzU2OTYyN15BMl5BanBnXkFtZTgwMTkwOTg2MTI@._V1_SX300.jpg'
    response['forum'] = forum1
    response['komentar'] = komentar
    page = request.GET.get('page', 1)
    paginator = Paginator(forum1, 3)
    navigasi = paginator.page(page)
    response['navigasi'] = navigasi
    return render(request,html,response)


# def model_to_dict(obj):
#     data = serializers.serialize('json',[obj,])
#     struct = json.loads(data)
#     data = json.dumps(struct[0]["fields"])
#     return data

# @csrf_exempt
# def add_comment (request,pk):
#     status = Reply.objects.get(pk=pk)
#     form = Comment_Form(request.POST or None)
#     if(request.method == 'POST' and form.is_valid()):
#         response['comment'] = request.POST['comment']
#         comment = Comment(comment=response['comment'])
#         comment.status = status
#         comment.save()
#         data = model_to_dict (comment)
#         return HttpResponse(data)
#     else:
#         return HttpResponseRedirect('/')

# def comment_post(request, post):
#     query = Update.objects.get(pk=post)
#     response['comment_form'] = Comment_Form
#     if(request.method == 'POST' and form.is_valid()):
#         response['comment'] = request.POST['comment']
#         comment = Update(message=response['comment'])
#         comment.save()
#         return HttpResponse('/comment')
#     else:
#         return HttpResponseRedirect('/comment')

def kumpulkan_komentar(forum):
    komentar = []

    for i in forum:
        a = Komentar.objects.filter(forum = i)
        for j in a:
            komentar.append(j)

    return komentar

@csrf_exempt
def add_comment(request):
    if request.method == 'POST':
        isi = request.POST['isi']
        nomor = request.POST['nomor']

        forum = Todo.objects.get(nomor = nomor)

        komentar = Komentar()
        komentar.forum = forum
        komentar.isi = isi
        komentar.nama = request.POST['nama']
        komentar.save()

        ambil = Komentar.objects.filter(isi = isi)

        return HttpResponse(status=200)
    else:
        return HttpResponse(status=403)

fitur2/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render

# Create your views here.
response = {}

def index(request) :
    print("==> masuk index")
    html = 'fitur2/fitur2.html'
    return render(request, html, response)

forum/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

import os

# Create your views here.
response = {}

def add_forum(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/company/forum/')
    else:
        return HttpResponseRedirect('/company/forum/')

def index(request):
    forum_list = Todo.objects.all()

    page = request.GET.get('page', 1)
    paginate_data = paginate_page(page, forum_list)
    forum = paginate_data['data']
    page_range = paginate_data['page_range']

    response = {"todo": forum, "todo_form": Todo_Form , "page_range" : page_range}
    html = 'forum/forum.html'
    return render(request, html, response)

def paginate_page(page, data_list):
    paginator = Paginator(data_list, 5)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1

    # maximum page
    max_index = len(paginator.page_range)

    # range of 10, slicing
    start_index = index if index >= 10 else 0
    end_index = 10 if index < max_index - 10 else max_index

    # Get our new page range. In the latest versions of Django page_range returns 
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data':data, 'page_range':page_range}
    return paginate_data

fitur1B/templates/fitur1B/fitur1B.html
{% extends "fitur1B/layout/base.html" %}
{% block content %}
<link href='https://fonts.googleapis.com/css?family=Kurale' rel='stylesheet'>
<style>

	#intro-txt {
		text-align: center;
		font-family: 'Kurale';
	}
	img {
		border-radius: 25px;
	}
	.lists {
		position: relative;
		text-align: center;
		color: white;
	}
	.tombol{
		text-align: center;
		display: flex;
		align-items: center;
		justify-content: center;
		
	}
	.button {
		background-color: #1a53ff;
		border: none;
		color: white;
		padding: 6px 26px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 12px;
		margin: 4px 2px;
		cursor: pointer;
		-webkit-transition-duration: 0.4s;
		transition-duration: 0.4s;
	}
</style>

<script type="text/javascript" src="//platform.linkedin.com/in.js">
	api_key: 81azw3ib6dwqzo
	onLoad: onLinkedInLoad
	authorize: true
</script>
<div class="container">
	<h1 class="hint" id="intro-txt"><strong>Welcome to ABCom, please login!</strong></h1>	
</div>

<hr>
<div class='col-md-9' >
    <section id="data-dashboard">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class='panel-title'> Forum </h2>
            </div>
            <div class="panel-body">
                {% if forum %}
                    {% for i in forum %}
                    {% with forloop.counter as counter1 %}
                        <div class='row'>
                            <div class='col-md-1'>
                                 {{ i.nomor }} .
                            </div>
                            <img src="{{ gambar }}" style='height:100px' class='col-md-2 img-responsive '/>
                            <div class='col-md-9'>
                                <div class='row'>
                                    <div class='col-md-9'>
                                        <h3  style='margin-top:0px'>{{ i.pengguna.company_name }}</h3>
                                        <p id='{{ counter1 }}'>{{ i.isi }}</p>
                                    </div>
                                    <button class='btn btn-default col-md-2' id='tombolBalas{{ forloop.counter }}' onclick="tambahKomentar( {{ i.nomor }} )">Balas</button>
                                    <button class='btn btn-danger col-md-2' id='tombolBatal{{ forloop.counter }}' style='display:none' onclick="batalKomentar( {{ forloop.counter }} )">Batal</button>
                                </div>
                            </div>
                        </div>
                        <hr/>

                        {% if komentar %}
                            {% for j in komentar %}
                                {% if j.forum.nomor == i.nomor %}
                                    <div class='row'>
                                        <div class='col-md-2'>

                                        </div>
                                        <img src="{{ gambar }}" style='height:100px' class='col-md-2 img-responsive '/>
                                        <div class='col-md-8'>
                                            <div class='row'>
                                                <div class='col-md-9'>
                                                    <h3  style='margin-top:0px'>{{ j.nama }}</h3>
                                                    <p id='{{ forloop.counter }}'>{{ j.isi }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr/>
                                {% endif %}
                            {% endfor %}
                        {% endif %}

                        <div class='row'>
                            <div class='col-md-3'></div>
                            <div class='col-md-7'  id='komentar{{ i.nomor }}'></div>
                        </div>

                    {% endwith %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Opps!</strong> Tidak ada Forum
                    </div>
                {% endif %}
            </div>

        </div>
	</section>
	
<hr>
<section>
	<div class="tombol">
		<button class="button button2" id="login">Login Mahasiswa</button>		
		<span style="display:inline-block; width: 300px;"></span>
		<!-- sign in with linkedin button -->
		<script type="in/Login" id="login"></script>
	</div>

</section>

<div class="line-separator"></div>
<!-- display profile info -->
<div id="profileData" style="display: none;">
    <p><a href="javascript:void(0);" class="button" onclick="logout()">Logout</a></p>
    <div id="picture"></div>
    <div class="info">
        <p id="name"></p>
        <p id="intro"></p>
        <p id="email"></p>
        <p id="location"></p>
		<p id="link"></p>
		<p>Work(s) at </p>
		<p id="companyLists" onclick="displayProfileCompany();"></p>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script>
    var tambahKomentar = function (angka) {
        var html =
        '<form>' +
        'Tulis Nama'+
        '<input class="form-control" id="tulisNama">' +
            '<div class="form-group">' +

            '<br>Tulis Komentar'+
              '<textarea class="form-control" rows="5" id="tulisKomentar"></textarea>' +
            '</div>' +

            '<div class="pull-right">' +
                '<a href="" class="btn btn-info" onclick=\"postKomentar(' + angka + ')\">Kirim</a>' +
            '</div>' +

        '</form>' ;

        $('#komentar' + angka).append(html);

        $('#tombolBalas' + angka).hide();
        $('#tombolBatal' + angka).show();

    };

    var batalKomentar = function (angka) {
        $('#komentar' + angka).html("");
        $('#tombolBalas' + angka).show();
        $('#tombolBatal' + angka).hide();
    }

    var postKomentar = function (angka) {
        // alert($('#' + angka).text());
            // alert(angka);
        $.ajax({
            async : false,
            method : 'POST',
            url : '{% url "fitur1B:add_comment" %}',
            data : {
            	'nama' : $('#tulisNama').val(),
                'isi' : $('#tulisKomentar').val(),
                'nomor' : angka
            },
        })
    }
</script>

{% endblock %}

fitur1B/templates/fitur1B/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<style>
    body {
        background-image: ()
		}
</style>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Login">
    <meta name="author" content="ABCom">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur1B.css' %}" />
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Login By {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
	{% include "fitur1B/partials/header.html" %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}
    {% include "fitur1B/partials/footer.html" %}
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/fitur1B.js' %}"></script>
</body>
</html>

fitur1B/templates/fitur1B/partials/footer.html
<div class="container-fluid">
    <h4>&copy; Made by AsikBanget Company Group 2 PPW B</h4>
</div>
<link href='https://fonts.googleapis.com/css?family=Kaushan Script' rel='stylesheet'>
<style>
    h4{
		position : bottom;
        text-align: center;
        color: black;
        font-family: 'Poppins';font-size: 13px;
    }
</style>

fitur1B/templates/fitur1B/partials/header.html
<nav class="navbar navbar-light" style="background: linear-gradient(to right, teal , pink)
">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=""><b>ABCom</b></a>
        
      </div>
      <div id="navbar" class="navbar-collapse collapse">

      </div><!--/.nav-collapse -->
    </div>
  </nav>

<link href='https://fonts.googleapis.com/css?family=Kaushan Script' rel='stylesheet'>
<style>
  .navbar-brand {
    font-family: 'Kaushan Script';font-size: 30px;
    color: #fff;
    outline: none;

  }

</style>

fitur2/templates/fitur2/fitur2.html
{% extends "fitur2/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Profile Perusahaan
{% endblock %}

{% block css %}
  <script type="text/javascript" src="//platform.linkedin.com/in.js">
  	api_key:   866hc1so0n9js9
  	onLoad:    onLinkedInLoadCompany
  	authorize: true
  </script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/fitur2.css' %}" />
{% endblock %}

{% block content %}
  <section style="height: auto;">
    <header class="masthead">
      <div class="overlay">
        <div class="container">
          <h3 class="display-1 text-white">Selamat Datang</h3>
          <h2 class="display-4 text-white" id="companyName"><center>ABCom<center></h2>
            <br>
            <p id="companyPicture" align = "center">
            <img src=http://cliparting.com/wp-content/uploads/2016/11/Small-office-building-clipart-kid.jpg widht="200" height="200" align = "center">
          </p>
          <br>
          <a href="/company/forum/" class="head-button"><center>Lihat Forum</center></a>
          <a href="#" class="head-button"><center>Cari Mahasiswa</center></a>
        </div>
      </div>
    </header>

    <div class="container" style="margin-top: 4%;" id="about-company-section">
      <div class="row">
        <div class="col-lg-11 col-md-11 col-sm-11 col-11 mx-auto">
          <h2 id="title-about">About Company:</h2>
          <div id="about"></div>
          <br>
          <div class="row">
            <div class="col-lg-6 col-md-4 col-sm-4 col-4" id="judul-about">
              <h5 id="about-company">Tipe Perusahaan</h5>
              <h5 id="about-company">Web Perusahaan</h5>
              <h5 id="about-company">Spesialitas</h5>
            </div>
            <div class="col-lg-6 col-md-8 col-sm-4 col-8">
              <h5 id="companyType"> Comercial</h5>
              <h5 id="companyWeb"> asikbanget.com</h5>
              <!-- : <a href="https://{{companyWeb}}">{{companyWeb}}<a> -->
              <h5 id="companySpecialty"> Web Advertising</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/fitur1.js' %}"></script>
{% endblock %}

fitur2/templates/fitur2/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Profile">
    <meta name="author" content="Kelompok 2">
    
    <title >
        {% block title %} Profile {% endblock %}
    </title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur2.css' %}">
</head>

<body>
    <header>
        {% include "fitur2/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur2/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur2/templates/fitur2/partials/footer.html
<nav class="navbar fixed-bottom">
    <a class="navbar-brand" href=""><p style="color:grey;">&copy; Made with Love by PPWB2</p></a>
</nav>

fitur2/templates/fitur2/partials/header.html
<nav>
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'fitur2:index' %}">Profile</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!-- <li><a href="">Input Todo</a></li>
          <li><a href="">My List</a> </li> -->
        </ul>
      </div>
    </div>
</nav>

forum/templates/forum/forum.html
{% extends "forum/layout/base.html" %}

{% block content %}
<h1 class="main-title">Forum Media Network</h1>
<hr/>
<section name="forum" id="forum">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2>Lowongan</h2>
                <hr/>
                <div class="list-group">
                    {% if todo %}
                    {% for data in todo %}
                        <div class="flex-item">
                            <div class="to-do-list">
                                <div class="to-do-list-title">
                                    <img class="img-circle" <img src=http://cliparting.com/wp-content/uploads/2016/11/Small-office-building-clipart-kid.jpg width="50" height="50">
                                    <h4>Media Network</h4>
                                </div>
                                <div class="to-do-list-date-added">
                                    Publish at {{data.created_date}}
                                </div>
                                <div class="to-do-list-description">
                                    {{data.description}}
                                </div>
                            </div>
                        </div>
                        <br>
                    {% endfor %}
                {% else %}
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Tidak ada forum.
                </div>
                {% endif %}
                {% if todo.has_other_pages %}
                    <div class="pagination">
                        {% if todo.has_previous %}
                            <li><a href="{% url 'forum:index' %}">&laquo;</a></li>
                            <li><a href="?page={{ todo.previous_page_number }}">&lsaquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&lsaquo;</span></li>
                        {% endif %}
                        {% for page in page_range %}
                            {% if todo.number == page %}
                                <li class="active"><span>{{ page }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if todo.has_next %}
                            <li><a href="?page={{ todo.next_page_number }}">&rsaquo;</a></li>
                            <li><a href="?page={{ todo.paginator.num_pages }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&rsaquo;</span></li>
                        {% endif %}
                    </div>
                {% endif %}     
                </div>
            </div>
            <div class="col-lg-4" name="input-list" id="input-list">
                <h2> Post </h2>
                <hr/>
                <form id="form" method="POST" action="{% url 'forum:add_forum' %}">
                    {% csrf_token %}
                    {{ todo_form }}
                    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                    <br>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

forum/templates/forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Forum">
    <meta name="author" content="Kelompok 2">
    
    <title>
        {% block title %} Forum {% endblock %}
    </title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
</head>

<body>
    <header>
        {% include "forum/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "forum/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

forum/templates/forum/partials/footer.html
<hr>

<div class="container-fluid">
    <h4>&copy; Made by AsikBanget Company Group 2 PPW B</h4>
</div>

forum/templates/forum/partials/header.html
<nav class="navbar navbar-default navbar-static-top" style="background-color: #EAF6F6;">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="" style="color:gold; font-weight:bold">Forum</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav nav-right pull-right">
          <li><a href="/company/profile/" style="color:gold; font-weight:bold">Profile</a></li>
          <li><a href="" onclick="" style="color:gold; font-weight:bold">Logout</a></li>
        </ul>
      </div>
    </div>
</nav>